### ISSUE TITLE
Remove AdvancedOnlineMarketing from Piwik marketplace

### ISSUE THREAD

**Issue by andre-hh** [advanced-online-marketing/AOM#10]
https://plugins.piwik.org/AdvancedOnlineMarketing is a duplicate of https://plugins.piwik.org/AOM which is buggy due to invalid namespacing.

We need to find out how to remove the buggy version.

See https://forum.piwik.org/t/how-to-remove-plugin-from-marketplace/19916.

**Comment by mikekerr247** [comment]
Hi Andre,

I haven't ever seen anyone change their plugin name once its on the marketplace so this might be a bug in their marketplace. 
There are a few things you might try if you haven't already but they might be a bad options:
- remove the webhook from github, wait a bit, and add the webhook again
- delete the releases associated with AdvancedOnlineMarketing

You should also try contacting Mattieu Aubry on the forum or github. He would probably want to know about a bug in his marketplace

**Comment by andre-hh** [comment]
Thank you! 

I have created an issue at the Piwik repo at https://github.com/piwik/piwik/issues/10256
