### ISSUE TITLE
visitor profile/summary: show total marketing costs and marketing efficiency 

### ISSUE THREAD

**Issue by hpvd** [advanced-online-marketing/AOM#12]
wow that's a nice new plugin. Many thanks for your work!

Would be informative to show total marketing costs and marketing efficiency in visitor profile/summary

please see attachment
![2016-06-24_11h39_22](https://cloud.githubusercontent.com/assets/5681880/16334617/45c49708-3a02-11e6-8a2e-524a7529e407.png)

**Comment by hpvd** [comment]
Do you know if it's possible from technical pov to extend the summary or should we open an issue within piwik?

btw: a little more detail and your own wording:
![2017-09-13_18h02_56](https://user-images.githubusercontent.com/5681880/30388085-e4b10b42-98ae-11e7-972c-19b9e5a28f02.png)

**Comment by hpvd** [comment]
just got the response: should be possible:
https://github.com/piwik/piwik/issues/6111#issuecomment-329228323

**Comment by andre-hh** [comment]
@hpvd, thank you very much for this proposal.
This has been been implemented with Piwik AOM 1.3.0.
