### ISSUE TITLE
Support custom prefixes for Piwik's tables

### ISSUE THREAD

**Issue by rpharrison** [advanced-online-marketing/AOM#19]
After installation of this plugin I was not able to successfully open the visitor popup. The following appears in error_log:

[29-Jul-2016 13:48:25 UTC] Error in Piwik: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;myuser_analytics.piwik_log_visit&#039; doesn&#039;t exist

It couldn't find piwik_log_visit because it was prefixed, i.e. myprefixedpiwik_log_visit

Change Commands/FixVisitAomParams.php, line 194

Platforms/Platform.php, line 295

and Commands/ReplenishVisits.php, line 392 to my prefixed table name and it works hard-coded.

**Comment by andre-hh** [comment]
Thanks, I have fixed that in version 0.3.7 which is out now.
