### ISSUE TITLE
Update plugin.json required version

### ISSUE THREAD

**Issue by tsteur** [advanced-online-marketing/AOM#20]
Hi there,

I'm Thomas from Piwik. We recently made some changes on the Marketplace and changed how versions are defined. In your plugin.json it defines:

```json
{"piwik":"2.15.0","php":"5.5.0"}
```

but in future updates it should include the `>=` and ideally include upper version constraint:

```json
{"piwik":">=2.15.0,<3.0.0-b1","php":">=5.5.0"}
```

Sorry for inconvenience and cheers

**Comment by danielstonies** [comment]
Will be fixed with the next release.
