### ISSUE TITLE
Prepare AOM for Piwik 3.0

### ISSUE THREAD

**Issue by andre-hh** [advanced-online-marketing/AOM#23]
Piwik 3.0 will be released early 2017 and there will be big changes. 
AOM should run on Piwik 3.0.

**Comment by dalmatele** [comment]
Your plugin is the best plugin I like.
Now Piwik's released 3.0 version so I hope you'll release your new version soon.
Thank you.

**Comment by andre-hh** [comment]
We'll do that in the next weeks. 👍

**Comment by casmartin** [comment]
Hi Andre, 
basically it is a great plugin, I even would downgrade to PIWIK 2. something because I need that glicd feature like the desert needs the rain. Could you give us an advice - will there come an update or are you to busy with other things?

**Comment by andre-hh** [comment]
Hi! We started work on the Piwik 3 migration in https://github.com/advanced-online-marketing/AOM/tree/feature/Piwik_3_Migration. From what I know, this branch should already work, but has not yet been tested in detail. If everything works out fine, we will release the Piwik 3 version until the end of February.

**Comment by casmartin** [comment]
Hii Andre,
could that be helpfull for you guys?

_Class 'Piwik\Plugins\AOM\Settings' not found
in
/home/bbla-bla/blub-blub/piwik/plugins/AOM/Controller.php line 22_

**Comment by casmartin** [comment]
wow - this is really high unethically - I tried it 2 days in all combinations PIWIK 3.0, PIWIK 2.17 and 2.16 by that I took of course care that I took the right AOM plugin ... later on I sent a mail  to Daniel to ask how that could work with these (pay) services, to find out if we could hire him for such a project  - but well, even that Email address which you publish on your page did not work ... so I guess it was never supposed to work ... it's extrem frustrating ...  :-(

**Comment by andre-hh** [comment]
The plug-in works at least for 2.16 but it is still a little hard to set up. Of course we would like to make the setup more convenient in the future. 

Thank you for letting us know that the e-mail-addresses are broken. I just fixed them. Daniel is currently on vacation, but I should be able to help out. What precise issues do you have with 2.17?

**Comment by casmartin** [comment]
Okay, 2.16 it is, I think I tried that, but let me check that one more time. By the way, I found this here 

Class 'Piwik\Plugins\AOM\Settings' not found in /home/thorbenj/public_html/piwik/plugins/AOM/Controller.php line 22


We could try to fix it on the weekend (we have the skills in House / Developers) for that - if you have any tip more, we we would be glad to know ... if not w may send you a solution Sunday / Monday ...

**Comment by casmartin** [comment]
Hi,
let me give you a feedback ... 

1. With 2.16.00 I could make it finally work, I get thhat 2.16  here: https://builds.piwik.org/ 
2. AOM is better than nothing, and it is a solid piece of work, however, when you run a remarketing campaign, it would be nice to have the referrer URL, but that seems not possible at all … seems like AOM deliver ... or  did II oversee something? I guess not… 


And well, it is possible to get the referrer URL, when you use in AdWords a tracking template and run dimension tracking in piwik … but that requires of course to make auto tagging off in AdWords off… and well, I hoped that AOM can catch that referrer data … for myself I remove AOM from my system but I keep it on the watch list  .. because one more time, AOM is a solid work – basically it is recommendable …

**Comment by andre-hh** [comment]
Thank you for your feedback! 

I think it is impossible to get the website where your remarketing campaign is being displayed as a HTTP_REFERRER as you are being redirected via an AdWords Google server and therefore the referrer would always bei Google. 

The only chance would be to get this data from the Google AdWords API, but I'm not sure if this only works for placement campaigns.

**Comment by casmartin** [comment]
Oaky, with AdWords auto tagging, I guess we can agree, you won’t get referrer URL – right?

However, when you put this in a tracking template:

{lpurl}?utm_source=AdWords&utm_medium=Remarketing&utm_campaign=xyz&utm_term={placement}&utm_content=xyz-Add-Group_name

than this {placement} will be replaced through referrer page URL … so how would that work in your opinion with aom_placement={placement}? Same way? – should be, no?

**Comment by andre-hh** [comment]
When using auto tagging, we get everything from the click report as described here: https://developers.google.com/adwords/api/docs/appendix/reports/click-performance-report

It did not check the current AdWords importer but we might get the placement from the click report in the field "CriteriaParameters".

I'll check that later on.

**Comment by casmartin** [comment]
I read your docs one more time ... and found this:

_"Limitations > Google AdWords Visits of Google display network are assigned on AdGroup level."_

So I guess  I was right yesterday when II said AOM "won't get the referrer URL..." buy the way, that counts as well for this  aom_placement={placement} - I tried that today ... 

Conclusion, if you need the referrer URL (Display or Remarketing) AOM won't be the right choice and you have to put this in your tracking template:  {lpurl}?utm_source=AdWords&utm_medium=Remarketing&utm_campaign=xyz&utm_term={placement}&utm_content=xyz-Add-Group_name

**Comment by andre-hh** [comment]
I'm quite busy currently but I took a close look into the piwik_aom_visits table and found that the placement should be assigned to the visit (see "keyword_placement"):

```
{
	"id": "10135",
	"id_account_internal": "...",
	"idsite": "1",
	"date": "2016-11-17",
	"account": "...",
	"campaign_id": "...",
	"campaign": "GDN - Placements",
	"ad_group_id": "8932937...",
	"ad_group": "LKW/Transporter",
	"keyword_id": "731602...",
	"keyword_placement": "suchen.mobile.de/lkw-inserat",
	"criteria_type": "placement",
	"network": "d",
	"impressions": "...",
	"clicks": "...",
	"cost": "...",
	"conversions": "...",
	"unique_hash": "1-2016-11-17-7c67ac2260fdfee8d7d803cef0e650ad",
	"ts_created": "2016-12-07 05:40:03"
}
```

This means it should be available within the data but it might not be displayed anywhere. I would really need some more time to dig into that specific topic.

**Comment by casmartin** [comment]
Hi,
I know, I read doc at least 5 times and I've seen this: "keyword_placement": "suchen.mobile.de/lkw-inserat",
But there I find either 'Undetermined' (Keyword ID 300) or  'Not a parent'  (Keyword ID 302) - strange Keyword Ids - no?

**Comment by danielstonies** [comment]
Piwik 3.0 support is available.
