### ISSUE TITLE
Can I join to contribute this project

### ISSUE THREAD

**Issue by dalmatele** [advanced-online-marketing/AOM#24]
Hi, I'm very interested with this project.
Now I've some ideas to extend it. Can I join to contribute to it?

**Comment by andre-hh** [comment]
Hi dalmatele! Thank you for asking. We would really like to see contributions of more developers to this Piwik plugin. Would be best if you would simply fork this project and create pull requests from it - see https://help.github.com/articles/working-with-forks/.

**Comment by dalmatele** [comment]
Ok, thank you :)
