### ISSUE TITLE
use gclid by default when no UTM tags are available in request 

### ISSUE THREAD

**Issue by RMastop** [advanced-online-marketing/AOM#25]
While setting up the plugin, one needs to decide whether to use gclid or UTM tags. 
It would be even more powerful to use UTM tags by default, with the fallback to gclid. This way there is no need to ask about it during the config.

**Comment by andre-hh** [comment]
You mean the Value Track based parameters like {prefix}_platform as described on http://www.advanced-online-marketing.com/advertisers-platforms.html and not "utm tags", correct?

We allowed the combination of Value Track based parameters and gclid at the same time in the first place (where Value Track based parameters were the fallback for gclid), but ran into issues where redirects removed the gclid but kept the Value Track based parameters which caused Piwik to assume the visitor would come from another advertisement and thus Piwik created a new separate visit for that. 

Although the configurable solution is less flexible, it should be more powerful in the long term. Based on gclid we should be able to implement more precise merging of visits with AdWords costs; we therefore might have two mainly independent AdWords mergers in the code later.

Makes sense?

**Comment by RMastop** [comment]
Yes, this clarifies the choice one has to make at setup.
Thanks.
