### ISSUE TITLE
Bing API Access Token provided by Bing, yet not able to enter in UI

### ISSUE THREAD

**Issue by amizzo87** [advanced-online-marketing/AOM#29]
When signing up for the Bing API, you are provided an access token, yet it can't be entered into the AOM UI within Piwik. Upon closer investigation, it seems `AOM/Platforms/Bing/Controller.php` has a lot of logic to handle processing of an access token returned in the callback from Bing, but it is not provided, throwing an error when clicking on "Refresh Token" and preventing the integration from succeeding.

Just wanted to point this out - let me know if I can help.

**Comment by amizzo87** [comment]
Nevermind, I misunderstood which "access token" it was referring to. Fixed in #30

**Comment by andre-hh** [comment]
Thank you very much for the PR! Merged it in version 0.5.6.
