### ISSUE TITLE
AOM causing index error on eMail Reports page

### ISSUE THREAD

**Issue by Micsi** [advanced-online-marketing/AOM#32]
Hi,

we get the following error when accessing the eMail reports config page with an existing report:

WARNING: /srv/www/laborumgebung/statistik/htdocs/plugins/ScheduledReports/ScheduledReports.php(197): Notice - Undefined index: category - Piwik 3.0.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

I was told that the problem is caused by plugins providing reports where the category is not set.

Disabling AOM solves the issue.

**Comment by andre-hh** [comment]
Thanks for letting us know.
This will be fixed with the next version.

**Comment by andre-hh** [comment]
This has been fixed in version 1.0.0.
