### ISSUE TITLE
Add account Button seams to be dead

### ISSUE THREAD

**Issue by hpvd** [advanced-online-marketing/AOM#33]
Add account Button seams to be dead (nothing happens on click) v0.69
![2017-06-26_11h34_33](https://user-images.githubusercontent.com/5681880/27533494-1120df7e-5a64-11e7-9a2d-66f96e994705.png)

**Comment by andre-hh** [comment]
I've clicked the button in my local environment and did not encounter any issues with that. 
Can you provide more details about the problem?

**Comment by hpvd** [comment]
thanks for checking.
just checked it again. Now it works fine.
maybe one has to log out and in after having updated your plugin, or piwik or...

could be closed

**Comment by andre-hh** [comment]
Thank you!
