### ISSUE TITLE
Can't add account in Piwik 3.0.4 with AOM 1.1.2

### ISSUE THREAD

**Issue by garantim** [advanced-online-marketing/AOM#37]
Hello,
I've just installed AOM 1.1.2 on my Piwik 3.0.4.
When I go on AOM settings page to add an account, I see the buttons but none of them work.
 (pressing but no actions happens, no logs).
I tried with Adwords, Bing, Criteo, Facebook Ads, Taboola and Individual campaigns.
I tried with chrome and firefox.
I just have non-clicking buttons.

Can you tell me what to do ?

**Comment by afterlastangel** [comment]
You should enable it in general setting page first 
<img width="1082" alt="screen shot 2017-07-29 at 9 45 06 pm" src="https://user-images.githubusercontent.com/1694449/28745676-2f6892bc-74a7-11e7-9640-a264fbc30459.png">

**Comment by garantim** [comment]
Thank you for your answer afterlastangel.
Sorry, I guess I haven't been clear enough in my explanations.
I have enabled this in the general setting page and I see the buttons but they are non-clickable.

I found out how to fix this : I copied the content of /Platforms/AdWords/javascripts/AdWords.js in /templates/settings.twig on line 83 and now adwords is working :)

I guess it is not the best way to fix this though ...

**Comment by afterlastangel** [comment]
Do you use any kind of adblocker? It might block anything related to adblock

**Comment by andre-hh** [comment]
You are right; an active AdBlocker might block the button's functionality.

**Comment by andre-hh** [comment]
@garantim did this solve your issue?
Perhaps it would help to rename the according fields?

**Comment by garantim** [comment]
I have upgrade the plugin with the 1.1.3 version this morning, and this is working fine now.

Thank you.

**Comment by andre-hh** [comment]
Thanks for the update!
