### ISSUE TITLE
Security: Accessability of aom.log and Matomo file integrity check

### ISSUE THREAD

**Issue by plastikschnitzer** [advanced-online-marketing/AOM#48]
Hello,

aom.log is located in the root directory of Matomo and public available via domain.tld/aom.log and it will show all your aom logs public.

Also Matomo file integrity check does not expect this file here and wants to delete, see Matomo system check.

Last but not least: If you have wrong credentials for an advertising platform, will it show on the logs like "login with: apikey and apisecret failed" or will the details be muted? To be honest: I do not want to test it ;-)

**Comment by andre-hh** [comment]
Thanks for sharing, this is a critical bug.

**Comment by danielstonies** [comment]
Log files can be configure in the next version in the config.ini.php.

Example:
[AOM]
log_file = /tmp/AOM.log
