### ISSUE TITLE
The plugin filename 'AOM-master/AOM-master.php' is not a valid plugin name

### ISSUE THREAD

**Issue by tkapler** [advanced-online-marketing/AOM#8]
I am not sure if this is a bug or i am just doing something wrong because this is the first piwik plugin i am instaling from github, not from marketplace. But when i follow the installation guide - downloaded the plugin and uploaded the AOM-master folder, that was in the ZIP it into my piwik/plugins folder, and then goes to admin, error page appears with message:
 The plugin filename 'AOM-master/AOM-master.php' is not a valid plugin name
I guess that the folder name should be "AOM" not "AOM-master" but when i chandged the folder name, the admin page show ERROR 500 page with no other information. 
I am using the latest piwik, the latest AOM, PHP 5.6

**Comment by andre-hh** [comment]
I have changed the instructions on http://www.advanced-online-marketing.com/docs.html. It is correct that the folder must be named "AOM" before ist uploaded. You might also clone the repository directly into your piwik plugin's folder. 

Did you run composer to install the plugin's dependencies?

You might find a more detailed error message somewhere, depending on the way your installation is being hosted.

**Comment by tkapler** [comment]
Thank you, i have not run composer to install the plugin's dependencies as i am testing it on shared hosting where i do not have the option to run composer. Tomorrow i will ask my admin to do it (but still anyway i think, that the plugin should not return error 500 in such case, and fully block the admin to load). Anyway thank you for your prompt response

**Comment by andre-hh** [comment]
You are absolutely right. The installation should be made a lot easier. I have created #9 for this.
